Adding bootstrap
castle-crew/chess-group-project pull request #1
Opened 2019-04-27 06:00 UTC by Kellysalito

Modified all the files needed to add bootstrap.

2019-04-27 18:01 UTC, KazimieraLuce requested changes
Looks good. Let's see if we can practice our first merge conflict since we both had to change the Gemfile 🤣

2019-04-27 18:01 UTC, KazimieraLuce approved these changes

2019-04-29 02:48 UTC, Kellysalito commented
So I'm a bit confused how to solve this with you.

2019-04-29 04:59 UTC, KazimieraLuce commented
> So I'm a bit confused how to solve this with you.

Hi Kelly, 

Sorry, the "request change" button was because I hit the wrong one when I added my comment. I thought I had hit the "Approve" one

2019-04-29 20:46 UTC, merged